[package]
name = "jrinx-testdef"
version = "0.1.0"
edition = "2021"

[dependencies]
jrinx-layout = { version = "0.1.0", path = "../layout" }
jrinx-testdef-macro = { version = "0.1.0", path = "../testdef-macro" }
